name: GRAPE
version: 4.8.1
date: 2018-10-24
description: |
    GRaph Algorithms using PErmutation groups

authors:
    - name: Leonard H. Soicher
      url: http://www.maths.qmul.ac.uk/~lsoicher/

maintainers:
    - name: Leonard H. Soicher
      url: http://www.maths.qmul.ac.uk/~lsoicher/

GAP: ">=4.9"

www: https://gap-packages.github.io/grape
readme: README
packageinfo: https://gap-packages.github.io/grape/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/grape/releases/download/v4.8.1/grape-4.8.1.tar.gz

abstract: |
    <span class="pkgname">GRAPE</span> is a package for computing with graphs and groups, and is primarily designed for constructing and analysing graphs related to groups, finite geometries, and designs.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    graph, geometry, design.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Soi18</span>]   <b class='BibAuthor'>Soicher, L. H.</b>,
     <i class='BibTitle'>GRAPE, GRaph Algorithms using PErmutation groups,
             Version 4.8.1</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/grape">https://gap-packages.github.io/grape</a></span>.
    </p>
    

bibtex: |
    @misc{ GRAPE4.8.1,
      author =           {Soicher, L. H.},
      title =            {{GRAPE},  GRaph  Algorithms  using PErmutation groups,
                          {V}ersion 4.8.1},
      month =            {Oct},
      year =             {2018},
      note =             {Refereed GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/grape}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{grape}}},
      keywords =         {graph; geometry; design},
      printedkey =       {Soi18}
    }

